## To modify by developper(s) of the plugin

[plugin-info]
SHORT_PLUGIN_NAME = 'optimisation'

package-url = 'https://github.com/PyMoDAQ/pymodaq_plugins_optimisation' #to modify
description = "PyMoDAQ's extension plugin to run optimisation algorithms"

author = 'Sebastien J. Weber'
author-email = 'sebastien.weber@cemes.fr'
license = 'MIT'

[plugin-install]
#packages required for your plugin:
packages-required = ['pymodaq>=4.0.0', 'pyfftw', 'scikit-image']
